# Generated by Django 3.2.24 on 2024-03-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focus',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
