# Generated by Django 3.2.24 on 2024-03-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0002_alter_focus_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focus',
            name='image',
            field=models.ImageField(blank=True, default='../default-focus_bpca53', upload_to='images/'),
        ),
    ]
