# Generated by Django 3.2.24 on 2024-03-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, default='../miscellaneous-tasks_b6f2gl', upload_to=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
