# Generated by Django 3.2.24 on 2024-03-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20240309_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
